module.exports = {
  BIRTH: 'Birth',
  BIRTH_CHILD: 'Birth_Child_Ref',
  BIRTH_DATE: 'Birth_Date_Ref',
  BIRTH_MOTHER: 'Birth_Mother_Ref',
  BIRTH_FATHER: 'Birth_Father_Ref',
  BIRTH_PLACE: 'Birth_Place_Ref',
  DATE: 'Date',
  DEATH: 'Death',
  DEATH_DATE: 'Death_Date_Ref',
  DEATH_PERSON: 'Death_Person_Ref',
  DEATH_PLACE: 'Death_Place_Ref',
  MARRIAGE: 'Marriage',
  MARRIAGE_DATE: 'Marriage_Date_Ref',
  MARRIAGE_SPOUSE: 'Marriage_Spouse_Ref',
  MARRIAGE_PLACE: 'Marriage_Place_Ref',
  NAME: 'Name',
  NAME_PERSON: 'Name_Person_Ref',
  PERSON: 'Person',
  PLACE: 'Place',
};
